### ISSUE TITLE
we have bindings to NLopt in ocaml

### ISSUE THREAD

**Issue by UnixJunkie** [tachukao/owl_lbfgs#1]
Not sure it matters to you, but there is nlopt-ocaml in opam.
And, that gives you access to a lot of optimizers (local/global, with/without gradient).

**Comment by tachukao** [comment]
> Not sure it matters to you, but there is nlopt-ocaml in opam.
> And, that gives you access to a lot of optimizers (local/global, with/without gradient).

thanks for the pointer! nlopt-ocaml looks really useful
